import type { Metadata } from 'next';
import './globals.css';
import Sidebar from '@/components/Sidebar';
import Navbar from '@/components/Navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="dark:bg-gray-800">
        <Navbar></Navbar>
        <Sidebar></Sidebar>
        <div className="block pt-[110px] pl-[285px] pr-7 pb-7 h-full w-full dark:bg-gray-800">{children}</div>
      </body>
    </html>
  );
}
